# GitHub Actions workflow for the Bitcoin Mining News Bot

name: Bitcoin Mining News Bot

on:
  schedule:
    # 1. Monitoring Workflow: Runs every 30 minutes to fetch and queue articles.
    - cron: '*/30 * * * *'
    # 2. Posting Workflow: Runs every 24 minutes to post from the queue.
    - cron: '*/24 * * * *'
    # 3. Daily Brief Workflow: Runs once per day at midnight UTC.
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering of all workflows for testing
    inputs:
      workflow:
        description: 'Which workflow to run'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - monitor
        - post
        - daily-brief

jobs:
  # Job 1: Monitoring Workflow
  monitor:
    name: 📰 Monitor News
    # Run this job only on its schedule or when manually dispatched
    if: |
      (github.event_name == 'schedule' && github.event.schedule == '*/30 * * * *') ||
      (github.event_name == 'workflow_dispatch' && (github.event.inputs.workflow == 'all' || github.event.inputs.workflow == 'monitor'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Monitoring Workflow
        env:
          EVENT_REGISTRY_API_KEY: ${{ secrets.EVENT_REGISTRY_API_KEY }}
        run: python main.py --workflow monitor

      - name: Commit and Push Queue Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add article_queue.json daily_brief_cache.json || true
          git diff --staged --quiet || git commit -m "Update article queue from monitor workflow [skip ci]"
          git push || true

  # Job 2: Posting Workflow
  post:
    name: 🐦 Post to Twitter
    # Run this job only on its schedule or when manually dispatched
    if: |
      (github.event_name == 'schedule' && github.event.schedule == '*/24 * * * *') ||
      (github.event_name == 'workflow_dispatch' && (github.event.inputs.workflow == 'all' || github.event.inputs.workflow == 'post'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Posting Workflow
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: python main.py --workflow post

      - name: Commit and Push Queue Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add article_queue.json posted_articles.json || true
          git diff --staged --quiet || git commit -m "Update article queue and posted articles from post workflow [skip ci]"
          git push || true

  # Job 3: Daily Brief Workflow
  daily-brief:
    name: 📚 Generate Daily Brief
    # Run this job only on its schedule or when manually dispatched
    if: |
      (github.event_name == 'schedule' && github.event.schedule == '0 0 * * *') ||
      (github.event_name == 'workflow_dispatch' && (github.event.inputs.workflow == 'all' || github.event.inputs.workflow == 'daily-brief'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Daily Brief Workflow
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python main.py --workflow daily-brief

      - name: Commit and Push Cache Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily_brief_cache.json || true
          git diff --staged --quiet || git commit -m "Update daily brief cache from daily-brief workflow [skip ci]"
          git push || true
